<program>:
  - ['<program">', '$']
<program">:
  - ['class', '%id%', '{', '<field_decl*>', '}']
<field_decl*>:
  - ['%type%', '<field_decl>', '<field_decl*_aux>']
<field_decl*_aux>:
  - ['<field_decl*>', '<field_decl*_aux>']
  - [null]
<field_decl>:
  - ['%id%', '<subscript>',';']
  - ['%id%', '<subscript>', '<comma_vars>', ';']
<comma_vars>:
  - [',', '%id%', '<subscript>', '<comma_vars>']
  - [null]
<subscript>:
  - ['[', '%int_literal%', ']']
  - [null]
