<program>:
  - ['<program">', '$']
<program">:
  - ['class', '%id%', '{', '<field_decl*>'  , '}']
  - ['class', '%id%', '{', '}']
<field_decl*>:
  - ['%type%', '%id%', '<subscript>', '<comma_vars>', ';']
  - ['%type%', '%id%', ';']
<subscript>:
  - ['[', '%int_literal%', ']']
<comma_vars>:
  - [',', '%id%', '<subscript>']
  - [',', '%id%']
