<program>:
  - ['<program^>', '$']
<program^>:
  - ['class', '%id%', '{', '<field_decl*>', '<method_decl*>', '}']
<field_decl*>:
  - ['%type%', '%id%', '<subscript>']
  - [null]
<subscript>:
  - ['[', '%int_literal%', ']']
  - [null]

<method_decl*>:
  - ['<type|void>', '%id%', '(', ')']
  - [null]
<type|void>:
  - ['%type%']
  - ['void']
