<program>:
  - ['<program">', '$']
<program">:
  - ['class', '%id%', '{', '<field_decl*>', '<method_decl*>', '}']
  - ['class', '%id%', '{', '<field_decl*>', '}']
  - ['class', '%id%', '{', '<method_decl*>', '}']
  - ['class', '%id%', '{', '}']
###############
# <field_decl*>
###############
<field_decl*>:
  - ['%type%', '<field_decl>', '<field_decl*_aux>']
<field_decl*_aux>:
  - ['<field_decl*>', '<field_decl*_aux>']
  - [null]
<field_decl>:
  - ['%id%', '<subscript>',';']
  - ['%id%', '<subscript>', '<var_array_list>', ';']
<var_array_list>:
  - [',', '%id%', '<subscript>', '<var_array_list>']
  - [null]
<subscript>:
  - ['[', '<expr>', ']']
  - [null]
###############
# <method_decl*>
###############
<method_decl*>:
  - ['def', '<type|void>', '%id%', '(', '<method_args>', ')', '<block>', '<method_decl*_aux>']
  - ['def', '<type|void>', '%id%', '(', ')', '<block>', '<method_decl*_aux>']
<method_decl*_aux>:
  - ['<method_decl*>', <method_decl*_aux>]
  - [null]
<type|void>:
  - ['%type%']
  - ['void']
<method_args>:
  - ['%type%', '%id%']
  - ['<method_args>', '<method_args">']
<method_args">:
  - [',', '%type%', '%id%', '<method_args">']
  - [null]
###############
# <block>
###############
<block>:
  - ['{', '<var_decl*>', '<statement*>', '}']
<var_decl*>:
  - ['<var_decl>', '<var_decl*>']
  - [null]
<statement*>:
  - ['<statement>', '<statement*>']
  - [null]
###############
# <var_decl>
###############
<var_decl>:
  - ['%type%', '%id%', '<args_list>', ';']
<args_list>:
  - [',', '%id%', '<args_list>']
  - [null]
###############
# <statement>
###############
<statement>:
  - ['%id%', '<subscript>', '<assign_op>', '<expr>', ';']
  - ['<method_call>', ';']
  - ['if', '<expr>', '<block>', '<else_block>']
  # - ['for', '(', '%id%', '%eq_op%', '<expr>', ')', '<block>']
  - ['return', ';']
  - ['return', '<expr>', ';']
  - ['break', ';']
  - ['continue', ';']
  - ['<block>']
  - ['<expr>', ';']
<else_block>:
  - ['else', '<block>']
  - [null]
###############
# <method_call>
###############
<method_call>:
  - ['%id%', '(', ')']
  - ['%id%', '(', '<comma_expr>', ')']
  - ['callout', '(', '<str>',  ')']
  - ['callout', '(', '<str>', '<comma_callout_arg>', ')']
<str>:
  - ['%string_literal%']
<comma_expr>:
  - ['<expr>', '<comma_expr">']
<comma_expr">:
  - [',', '<expr>', '<comma_expr">']
  - [null]
<comma_callout_arg>:
  - ['<callout_arg>', <comma_callout_arg">]
<comma_callout_arg">:
  - [',', '<callout_arg>', '<comma_callout_arg">']
  - [null]
###############
# <method_name>
###############
# <method_name>:
#   - ['%id%']
###############
# <expr>
###############
<expr>:
  - ['%id%', '<subscript>']
  - ['<literal>']
  - ['<expr>', '<bin_op>', '<expr>']
  - ['%minus%', '<expr>']
  - ['!', '<expr>']
  - ['(', '<expr>', ')']
  # - ['<expr>', '<expr>']
###############
# <location>
###############
# <location>:
#   - ['%id%']
#   - ['%id%', '[', '<expr>', ']']
###############
# <callout_arg>
###############
<callout_arg>:
  # - ['<expr>']
  - ['%string_literal%']
###############
# <bin_op>
###############
<bin_op>:
  - ['<arith_op>']
  - ['%rel_op%']
  - ['%eq_op%']
  - ['%cond_op%']
###############
# <literal>
###############
<literal>:
  - ['%int_literal%']
  - ['%char_literal%']
  - ['%bool_literal%']
<assign_op>:
  - ['%assign%']
  - ['%assign_inc%']
  - ['%assign_dec%']
<arith_op>:
  - ['%plus%']
  - ['%minus%']
  - ['%mult%']
  - ['%div%']
  - ['%mod%']
